server:
  port: 8001

spring:
  application:
      name: service1

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/